### ISSUE TITLE
Suggestion: Use a CMS

### ISSUE THREAD

**Issue by gouthamve** [LambdaIITH/Dashboard-Old#2]
CMS will increase your productivity 10x. Try keystonejs.com

**Comment by CrazyByDefault** [comment]
# Nice point.

**Comment by hsharsh** [comment]
We understand your concern, but we don't view this project as a 1-month hackathon. We want to take this project forward and implement it as soon as possible.

**Comment by gouthamve** [comment]
Lol? Bro. Some CMS's like Keystone scale! And abstract out a lot of complexity. To do this from scratch is like re-implementing a lot of the same functionality.

Any good reason to not use a CMS?

**Comment by ayushpateria** [comment]
We can use KeystoneJS but I don't understand how can it help us exactly. As far as I understand the only thing we will get using KeystoneJS is an admin interface to manage everything. But do we really need it? I think we don't need anyone with the 'admin' role managing the app. The app is self reliant and the user will be having such interfaces like say to change his courses. Tell me if I am missing anything.

**Comment by gouthamve** [comment]
Haha. I agree. But now it also brings into picture a number of helpers (Like S3 uploading, User management, etc.) @thecodesome can shed some light maybe.

Anyways, this is something I feel strongly about but, I guess anything works, so I did not re-open the issue.

**Comment by codesome** [comment]
@prateekkumarweb can tell better about this (as he has worked a lot with it)
